version: "3.7"
services:
    php:
        image: rsnstkw/web
        volumes:
            - ./web-db/web:/var/www/html/
        ports:
            - '9000:9000'
    nginx:
        image: rsnstkw/nginx
        volumes:
            - ./web-db/web/:/var/www/html/
        deploy:
            replicas: 3
        links:
            - 'php'
        ports:
            - '8080:80'
    db:
        image: rsnstkw/db
        environment:
            MYSQL_ROOT_PASSWORD: 12345
        ports:
            - 3306:3306
        links:
            - 'nginx'
            - 'php'
